DROP ROLE IF EXISTS DBA,
AUTHORIZATION_TEAM,
UI_TEAM
MARKETING_TEAM,
MANAGEMENT_TEAM,
MEDICAL_TEAM,
DOCTORS;

CREATE USER DBA WITH ENCRYPTED PASSWORD 'ADMIN123';

GRANT ALL PRIVILEGES ON DATABASE PROJECT TO DBA;

CREATE USER AUTHORIZATION_TEAM WITH ENCRYPTED PASSWORD 'AUTH123';

GRANT ALL ON TABLE LOGIN_PUBLIC,
LOGIN_ZOO,
LOGIN_PET_SHOP,
LOGIN_ANIMAL_SHELTER,
LOGIN_DOCTORS TO AUTHORIZATION_TEAM;

CREATE USER UI_TEAM WITH ENCRYPTED PASSWORD 'UI123';

GRANT
SELECT
  ON TABLE ANIMAL_SHELTER,
  PET_SHOP,
  ZOOS,
  ANIMAL_TYPE,
  PET_CARE_PRODUCTS,
  ANIMAL,
  ANIMAL_ADOPTED TO UI_TEAM;

CREATE USER MARKETING_TEAM WITH ENCRYPTED PASSWORD 'MRKT123';

GRANT
SELECT
  (general_public_email, general_public_phone) ON TABLE GENERAL_PUBLIC TO MARKETING_TEAM;

CREATE USER MANAGEMENT_TEAM WITH ENCRYPTED PASSWORD 'MGMT123';

GRANT ALL ON TABLE ANIMAL_SHELTER,
PET_SHOP,
ZOOS,
ANIMAL_TYPE,
PET_CARE_PRODUCTS,
ANIMAL,
ANIMAL_ADOPTED TO MANAGEMENT_TEAM;

CREATE USER MEDICAL_TEAM WITH ENCRYPTED PASSWORD 'MT123';

GRANT
SELECT
  ON TABLE ANIMAL_ANIMAL_DISEASE_HISTORY TO MEDICAL_TEAM;

CREATE USER DOCTORS WITH ENCRYPTED PASSWORD 'AB23';

GRANT
SELECT
,
INSERT
,
UPDATE
  ON TABLE ANIMAL_ANIMAL_DISEASE_HISTORY,
  QUERIES_QUERY_ANSWER,
  ANIMAL_TYPE_ANIMAL_TYPE_CARE TO DOCTORS;
